package modelos;
// Generated 15 ene 2026, 18:39:43 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private Integer idCliente;
	private String nombre;
	private String apellidos;
	private String direccion;
	private Integer edad;
	private Set inscripcioneses = new HashSet(0);

	public Cliente() {
	}

	public Cliente(String nombre, String apellidos, String direccion, Integer edad, Set inscripcioneses) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.direccion = direccion;
		this.edad = edad;
		this.inscripcioneses = inscripcioneses;
	}

	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	public Set getInscripcioneses() {
		return this.inscripcioneses;
	}

	public void setInscripcioneses(Set inscripcioneses) {
		this.inscripcioneses = inscripcioneses;
	}

	@Override
	public String toString() {
	    return "Cliente #" + idCliente + " - " + nombre + " " + apellidos + 
	           " | Dirección: " + direccion + " | Edad: " + edad + " años";
	}

}
