package modelos;
// Generated 15 ene 2026, 18:39:43 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cursos generated by hbm2java
 */
public class Curso implements java.io.Serializable {

	private Integer idCurso;
	private String nombreCurso;
	private String descripcion;
	private Integer duracion;
	private Set inscripcioneses = new HashSet(0);

	public Curso() {
	}

	public Curso(String nombreCurso, String descripcion, Integer duracion, Set inscripcioneses) {
		this.nombreCurso = nombreCurso;
		this.descripcion = descripcion;
		this.duracion = duracion;
		this.inscripcioneses = inscripcioneses;
	}

	public Integer getIdCurso() {
		return this.idCurso;
	}

	public void setIdCurso(Integer idCurso) {
		this.idCurso = idCurso;
	}

	public String getNombreCurso() {
		return this.nombreCurso;
	}

	public void setNombreCurso(String nombreCurso) {
		this.nombreCurso = nombreCurso;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getDuracion() {
		return this.duracion;
	}

	public void setDuracion(Integer duracion) {
		this.duracion = duracion;
	}

	public Set getInscripcioneses() {
		return this.inscripcioneses;
	}

	public void setInscripcioneses(Set inscripcioneses) {
		this.inscripcioneses = inscripcioneses;
	}

	@Override
	public String toString() {
	    return "Curso #" + idCurso + " - " + nombreCurso + 
	           " | " + descripcion + " | Duración: " + duracion + " horas";
	}

}
