package modelos;
// Generated 15 ene 2026, 18:39:43 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Inscripciones generated by hbm2java
 */
public class Inscripcion implements java.io.Serializable {

	private Integer idInscripcion;
	private Curso cursos;
	private Cliente clientes;
	private Date fechaInscripcion;

	public Inscripcion() {
	}

	public Inscripcion(Curso cursos, Cliente clientes) {
		this.cursos = cursos;
		this.clientes = clientes;
	}

	public Inscripcion(Curso cursos, Cliente clientes, Date fechaInscripcion) {
		this.cursos = cursos;
		this.clientes = clientes;
		this.fechaInscripcion = fechaInscripcion;
	}

	public Integer getIdInscripcion() {
		return this.idInscripcion;
	}

	public void setIdInscripcion(Integer idInscripcion) {
		this.idInscripcion = idInscripcion;
	}

	public Curso getCursos() {
		return this.cursos;
	}

	public void setCursos(Curso cursos) {
		this.cursos = cursos;
	}

	public Cliente getClientes() {
		return this.clientes;
	}

	public void setClientes(Cliente clientes) {
		this.clientes = clientes;
	}

	public Date getFechaInscripcion() {
		return this.fechaInscripcion;
	}

	public void setFechaInscripcion(Date fechaInscripcion) {
		this.fechaInscripcion = fechaInscripcion;
	}

	@Override
	public String toString() {
		String nombreCliente = clientes.getNombre() ;
		String nombreCurso =cursos.getNombreCurso();

		return "Inscripción #" + idInscripcion + " | Cliente: " + nombreCliente + " | Curso: " + nombreCurso
				+ " | Fecha: " + fechaInscripcion;
	}

}
